output "Disk" { value = "${digitalocean_droplet.vm.*.disk}" }
output "Droplet-ID" { value = "${digitalocean_droplet.vm.*.id}" }
output "Image" { value = "${digitalocean_droplet.vm.*.image}" }
output "public-ipv4" { value = "${digitalocean_droplet.vm.*.ipv4_address}" }
output "private-ipv4" { value = "${digitalocean_droplet.vm.*.ipv4_address_private}" }
output "IPv6" { value = "${digitalocean_droplet.vm.*.ipv6}" }
output "public-ipv6" { value = "${digitalocean_droplet.vm.*.ipv6_address}" }
output "private-ipv6" { value = "${digitalocean_droplet.vm.*.ipv6_address_private}" }
output "Locked" { value = "${digitalocean_droplet.vm.*.locked}" }
output "Name" { value = "${digitalocean_droplet.vm.*.name}" }
output "hourly-price" { value = "${digitalocean_droplet.vm.*.price_hourly}" }
output "monthly-prce" { value = "${digitalocean_droplet.vm.*.price_monthly}" }
output "private-networking" { value = "${digitalocean_droplet.vm.*.private_networking }" }
output "Region" { value = "${digitalocean_droplet.vm.*.region }" }
output "Size" { value = "${digitalocean_droplet.vm.*.size }" }
output "Status" { value = "${digitalocean_droplet.vm.*.status }" }
output "Tags" { value = "${digitalocean_droplet.vm.*.tags }" }
output "VCPUs" { value = "${digitalocean_droplet.vm.*.vcpus }" }
